language: python

python:
    - 2.6
    - 2.7

before_install:
    - sudo apt-get update
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.6.0-Linux-x86_64.sh -O miniconda.sh; fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - hash -r

install:
    - conda update --yes conda
    - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
    - source activate testenv
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install ordereddict; fi
    - conda install --yes numpy scipy
    - git clone https://github.com/neurospin/caps-mmutils.git /tmp/caps-mmutils
    - export PYTHONPATH=$PYTHONPATH:/tmp/caps-mmutils
    - pip install ez_setup
    - pip install soma-workflow
    - pip install capsul
    - pip install matplotlib
    - pip install nibabel
    - pip install pydicom
    - pip install nose
    - pip install nose-exclude
    - pip install coverage
    - pip install coveralls
    - pip install pep8
    - git clone -b glossary https://github.com/AGrigis/capsul.git /tmp/capsul
    - export PYTHONPATH=$PYTHONPATH:/tmp/capsul
    - python setup.py install

script:
    - python setup.py nosetests
    - pep8 . --ignore="E121,E123,E126,E226,E24,E704,E402"

after_success:
    - cat .coverage | wc
    - coveralls


